### ISSUE TITLE
Feedback Milestone 2

### ISSUE THREAD

**Issue by SuzanaMomo** [data301-2021-summer2/project-group45-project#1]
Hello,

My name is Suzana and I will be giving you some feedback on your project.

Overall, the project is a good starting point, but there is some work that needs to be done to elevate this project to our standards so its meets our expectations. 

I have divided up the feedback into several sections so it is easier for you to implement.

## Task 1
Good job
## Task 2
Good job

## Task 3
- [x] Your plots need to be more clear, i.e with proper legends, labels, explanation. The purpose of some of the plots were unclear to me and most of them did not have proper legends or they were overlapping among themselves.

## Task 4

- [x] Organize your tasks. Each research question (statement) then their plots (visualization) and then its explanation. Maintain this serial for every research question.
- [x] Along with the existing plots try have another type of plots that will help visualize your research questions more
